const allLanguages = {
  AF: "Afrikaans",
  SQ: "Albanian",
  AR: "Arabic",
  EU: "Basque",
  BG: "Bulgarian",
  CA: "Catalan",
  ZH: "Chinese",
  HR: "Croatian",
  CS: "Czech",
  DA: "Danish",
  NL: "Dutch",
  EN: "English",
  ET: "Estonian",
  FI: "Finnish",
  FR: "French",
  DE: "German",
  EL: "Greek",
  HE: "Hebrew",
  HI: "Hindi",
  HU: "Hungarian",
  IS: "Icelandic",
  IN: "Indonesian",
  IT: "Italian",
  JA: "Japanese",
  KO: "Korean",
  LV: "Latvian",
  LT: "Lithuanian	",
  MK: "Macedonian",
  MS: "Malay",
  NO: "Norwegian",
  PL: "Polish",
  PT: "Portuguese",
  RM: "Raeto-Romance",
  RO: "Romanian",
  RU: "Russian",
  SR: "Serbian",
  SL: "Slovak",
  SK: "Slovenian",
  ES: "Spanish",
  SV: "Swedish",
  TR: "Thai",
  TH: "Turkish",
  VI: "Vietnamese",
};
export default allLanguages;
